# A pre-commit hook.
# See: https://pre-commit.com/

- id: alacritty-osspecific-shell
  name: Alacritty OS specific shell
  description: This hook sets the alacritty shell program os-specific. Used on an cross-os dotfiles repo.
  entry: set-alacritty-shell
  language: python
  files: alacritty.yml
