# A pre-commit hook.
# See: https://pre-commit.com/

- id: alacritty-os-specific-shell
  name: Alacritty OS specific shell
  description: This hook sets alacritty shell.program os-specific. Used on cross-os dotfile repos.
  entry: setalacrittyshell
  language: python
  files: alacritty\.yml$
