[project]
name = "pre-commit-alacritty-osspecific-shell"
version = "0.1.0"
description = "This hook sets alacritty shell.program os-specific. Used on cross-os dotfiles repos."
requires-python = ">=3.10"

[project.scripts]
set-alacritty-shell = "hook:main"
